runner:
  total_steps: 10000
  gradient_clipping: 1
  gradient_accumulate_steps: 8   # default: 5

  log_step: 500
  eval_step: 500
  save_step: 500
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: Adam   # default AdamW
  lr: 1.0e-4   # default 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 1400

downstream_expert:
  datarc:
    data_dir: /data/CMU-MOSEI/Audio
    label_dir: ./downstream/mosei/utility/CMU_MOSEI_Labels.csv
    num_class: 6
    num_workers: 12 
    train_batch_size: 2
    eval_batch_size: 1 

  modelrc:
    input_dim: 256
    projector_dim: 256
    select: UtteranceLevel

    UtteranceLevel:
      pooling: MeanPooling

    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 160
      kernel_size: 10
      padding: 4
      pooling: 10
      dropout: 0.1
